### ISSUE TITLE
Deeper Stratagem

### ISSUE THREAD

**Issue by Natlyz** [rgd87/NugComboBar#11]
**Hello!**

Please, allow us to use separate profiles for Subtlety with and without the [Deeper Stratagem] talent. Same way as we can have different profiles for different specs.

![depstr](https://user-images.githubusercontent.com/60573947/103715094-cc0b0c00-4fd0-11eb-9a4b-3d6cecd243ba.png)

Deeper Stratagem could be like 4th spec in the addon window.

**Thanks 😊**

**Comment by d87** [comment]
Hi, no deeper stratagem can't be a spec. Why do you need it? If you're having problems with variable frame size, try different anchor positions, with that you can have it growth left/right or be centered

**Comment by Natlyz** [comment]
Hello, I can't seem to find a different anchor point so it's always centered, but the thing is I'd like a differently coloured CPs for 5th or 6th CP with or without the talent.

**Comment by d87** [comment]
https://github.com/rgd87/NugComboBar/releases/tag/9.0.9-beta1

Here there's an option to recolor all points when full

**Comment by Natlyz** [comment]
Thanks, I'll try it.
