### ISSUE TITLE
Broken on Classic

### ISSUE THREAD

**Issue by aboose-aboose-aboose** [rgd87/NugComboBar#14]
Date: 2021-04-23 01:41:29
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\NugComboBar\Options\NugComboBarGUI.lua line 739:
   attempt to call global 'GetNumSpecializations' (a nil value)
Debug:
   [C]: GetNumSpecializations()
   ...erface\AddOns\NugComboBar\Options\NugComboBarGUI.lua:739: in main chunk
   [C]: ?
   [C]: LoadAddOn()
   NugComboBar\NugComboBar.lua:1069: ?()
   NugComboBar\NugComboBar.lua:1135: ?()
   ..\FrameXML\ChatFrame.lua:4697: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4360: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4396:
      ..\FrameXML\ChatFrame.lua:4392
   [C]: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1

Doesn't appear, when calling NCB GUI I get the above.

**Comment by d87** [comment]
Looks like you installed retail version

**Comment by aboose-aboose-aboose** [comment]
Hi, I had been using this for years and it worked well. I use Ajour to update my addons and an update pushed thru yesterday and started causing this issue for both nugenergy and nugcombopoints. I downloaded nugenergy manually from your github and replaced folder and it fixed, but when I copy 9.0.9 of NugComboBar it just gives me the above error still. 

I probably caused this problem myself with teh updater, but where can I get a clean classic version?

**Comment by d87** [comment]
https://github.com/rgd87/NugComboBar/releases/tag/1.13.9-tbc1

**Comment by aboose-aboose-aboose** [comment]
Perfect ty, it works. I got confused bc it said TBC
