### ISSUE TITLE
frame won't show when changing specs

### ISSUE THREAD

**Issue by hollo6** [rgd87/NugComboBar#16]
On a druid, when changing spec to Feral, the frame won't appear until reloading.
Doesn't seem to affect other classes, so I guess it has to do with druids not using combo points in other specs.

**Comment by hollo6** [comment]
This is still happening... any chance of a fix or at least workaround?

**Comment by d87** [comment]
Which game version is that? Wrath?

**Comment by d87** [comment]
Ok, should be fixed in 10.2.3

**Comment by hollo6** [comment]
Seems good now, thanks!
