### ISSUE TITLE
Assassination shows 6 CPs instead of 7CPs

### ISSUE THREAD

**Issue by Narvas98** [rgd87/NugComboBar#21]
Hey,

i have an Issue with Assassination, with TWW Prepatch Assassinations Rogues can have 7 Combopoints. The Problem probably is that its a new Spell.

https://www.wowhead.com/spell=457512/sanguine-stratagem

**Comment by Narvas98** [comment]
`local DeeperStratagem = IsPlayerSpell(193531) and 1 or 0 -- Deeper Stratagem
        local DeviousStratagem = IsPlayerSpell(394321) and 1 or 0 -- Deeper Stratagem
        local SecretStratagem = IsPlayerSpell(394320) and 1 or 0 -- Secret Stratagem
        local SanguineStratagem = IsPlayerSpell(457512) and 1  or 0 -- Sanguine Stratagem
        local maxCP = 5 + DeeperStratagem + DeviousStratagem + SecretStratagem + SanguineStratagem`

**Comment by d87** [comment]
Thanks, fixed
