### ISSUE TITLE
Mistweaver Support

### ISSUE THREAD

**Issue by DenL** [rgd87/NugComboBar#7]
Hello, currently on Monk-Mistweaver, the combo bar show support for "Teachings of the Monastery" stacks. Is it possible to add support (perhaps an option to select between the two) for "Renewing Mists" charges? Similar to Protection Paladin's Shield of the Righteous support. Thank you!

**Comment by d87** [comment]
Alright, done in https://github.com/rgd87/NugComboBar/commit/1d44205ae947b4ead71ebdeffcb1ec5caf34c066
